### ISSUE TITLE
Cannot execute on localhost with Deno

### ISSUE THREAD

**Issue by dangvanthanh** [liamtan28/dactyl#18]
When I running deno application using `dactyl`, I see an error:

![dactyl](https://user-images.githubusercontent.com/2674850/89733600-ae1c9800-da80-11ea-9517-715249127f1d.png) 

I check the version in `https://deno.land/x/dactyl@v0.1.0-alpha/deps.ts`, version of **std** is `std@0.51.0` but in the current version in `master` branch is `std@0.62.0`

https://github.com/liamtan28/dactyl/blob/0ccf4d81f4318d811bf5d49e230b97923cbd4eaa/deps.ts#L14

I think you should upgrade the module in deno. Thank you very much.

**Comment by liamtan28** [comment]
Hi there - this has been patched on master a few days ago. Pulling from latest will fix this for you. I can put through a patched version tonight(v0.1.1-alpha)

**Comment by dangvanthanh** [comment]
Hi @liamtan28 

The issues cannot resolve. Can you re-check again?
